### ISSUE TITLE
How to deal with black not being black

### ISSUE THREAD

**Issue by jonathantneal** [Esri/calcite-web#843] opened 2017-08-03 12:25 UTC
Very often, I’m working with designs that use **black** (`#000000`), which is darker than the darkest **black** in Calcite (`#323232`).

What strategy do you recommend we mortal developers follow to handle this?

Has anyone [paved a cowpath](https://en.wiktionary.org/wiki/pave_the_cowpath) for this **actual-black**, **true-black**, **dark-black**, **no-really-this-time-its-black** color?

May be related to the 11 step grayscale developed in https://github.com/Esri/calcite-web/issues/32

**Comment by paulcpederson** [comment] 2017-08-03 16:58
@jonathantneal true black is not in the brand colors: https://github.com/Esri/calcite-colors/blob/master/scss/variables.scss

**Comment by jonathantneal** [comment] 2017-08-03 17:10
I suppose it’s too late to rename `black` to `brand-black`?

@bstifle, any insights?

**Comment by bstifle** [comment] 2017-08-03 17:13
i'd love for our colors to be more mindful. im pretty sure @kyle-03674 had a solve for this in the new color system

**Comment by paulcpederson** [comment] 2017-08-03 17:15
@jonathantneal you can also call it by its *true* name `$Calcite_Gray_700` if that strikes your fancy

**Comment by jonathantneal** [comment] 2017-08-03 17:28
@paulcpederson, it’s slightly less confusing, but it might help if I can associate it with meaning. What does the `700` mean?

I’m interested in learning what @kyle-03674’s solution was for this. That may be a suitable resolution.

It seems Calcite doesn’t otherwise have anything to do with true black (`#000000`), except when it’s [`$white`](https://github.com/Esri/calcite-web/blob/17e19cc7ad60a7600e83a8f2321c7985119ef92f/lib/sass/calcite-web-dark.scss#L150).

**Comment by paulcpederson** [comment] 2017-08-03 17:30
Yep, that's accurate. That is by design as far as I can tell. Calcite Web doesn't control these hex values, so there isn't much we can do about it here.

**Comment by jgravois** [comment] 2017-08-03 23:48
> how much more black could this be?
the answer is none. [none more black](https://www.youtube.com/watch?v=46kXH6GGtT0).

**Comment by julio8a** [comment] 2017-08-10 16:55
from Operations Dashboard perspective:

We use `$white` quite a bit on Dashboard. However, when we switch to dark theme all that white converts to black, which makes the Dashboard look like a high-contrast UI. There are some places where we leave the `black`, but in most elements, we override black on dark theme.  :(

**Comment by kyle-03674** [comment] 2017-08-17 22:28
... I was out for a while and am still digging out from all the things I missed, so thanks for your patience @bstifle and others.

The intent of Calcite colors was to not use true black. In the case of the darkest Calcite gray `$Calcite_Gray_700` in default light theme it's value is #323232 but in dark theme it's #d1d1d1. Whereas white, otherwise known as `$Calcite_Gray_050` or #ffffff changes to #242424 in dark theme. Maybe that's still too contrasty, like @julio8a  was saying, but it's still better than pure black. The intent was to preserve `$Calcite_Gray_700` for times when you needed an accent, and use `$Calcite_Gray_650` for most dark color purposes.

In the new system, which is still pending approval by Steven and Stefanie, gray values are much more straightforward, with even steps from pure white to pure black. The dark theme is simply inverted.  This might not give the perfect light-to-dark theme conversion, but at least the steps are predictable. See these two screenshots:

![screen shot 2017-08-17 at 3 20 43 pm](https://user-images.githubusercontent.com/11050471/29436446-67926934-8360-11e7-82fa-ebe2469ca650.png)
![screen shot 2017-08-17 at 3 20 34 pm](https://user-images.githubusercontent.com/11050471/29436445-679042bc-8360-11e7-820e-37aa14181b6a.png)


@jonathantneal yes, it's too late to rename the Calcite colors :)  but to answer your question, the grays in the current system were selected based on those colors used most frequently in all types of UI design at the time they were created, about 4 years ago, with revisions about 2 years ago. Cassidy and I worked on those.

**Comment by julio8a** [comment] 2017-08-17 22:36
@kyle-03674 `#242424` would work great for us!

**Comment by kyle-03674** [comment] 2017-08-17 22:40
@julio8a that color value is in [this PDF in the old "patterns" Box folder](https://esri.app.box.com/file/41893328194) but I'm not sure if it's in the variables? I think so. Either way, I believe you're just entering the hex value for Operations Dashboard?

**Comment by julio8a** [comment] 2017-08-17 22:45
@kyle-03674, Yes. We created a new variable called `$dashboard-dark: #222222`.  If we can get the variable `$white` from calcite web to display `#242424` on dark theme, that would be great. We can get rid of the new variable we created and just use default Calcite-Web.  

Right now variable `$white` on light theme is `#ffffff` and `#000000` on dark theme.

**Comment by kyle-03674** [comment] 2017-08-17 22:57
What is $Calcite_Gray_050 on light theme and dark theme right now?

**Comment by bstifle** [comment] 2017-08-18 16:57
@kyle-03674  so KK-00 is #000000?

We use true black (#000000) sparingly, but _we do use it_.

**Comment by kyle-03674** [comment] 2017-08-18 17:42
@bstifle yes, in light theme KK-00 is `#000000` and in dark theme it's `#ffffff`

**Comment by kyle-03674** [comment] 2017-08-18 17:42
that is, *will be* those values once they're adopted

**Comment by paulcpederson** [comment] 2017-11-03 21:44
I'm going to close this, and we can address black when the new system is adopted and we update everything to use it.

**Closed by paulcpederson** 2017-11-03 21:44 UTC
