### ISSUE TITLE
Modal windows still allow the page to be scrolled

### ISSUE THREAD

**Issue by RalucaNicola** [Esri/calcite-web#822] opened 2017-06-26 14:26 UTC
For the [Web Style Symbols](https://developers.arcgis.com/javascript/latest/guide/esri-web-style-symbols/index.html) page we use calcite modal windows. Scrolling on top of the window, scrolls the page behind it:
![modal-window](https://user-images.githubusercontent.com/8091967/27544020-32faa22e-5a8c-11e7-92ff-c89bca568cb7.gif)

**Comment by paulcpederson** [comment] 2017-06-26 16:35
This is a duplicate of #766 I'm working on a fix for rc7

**Closed by paulcpederson** 2017-06-26 16:35 UTC
