### ISSUE TITLE
Some Russian characters are rendered taller than others

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-web#967] opened 2018-07-31 18:30 UTC
Started with the Quickstart, changed the html tag to `<html lang="ru" dir="ltr">`, and added the text "Помогающие агентства становятся более устойчивыми, разрабатывают планы готовности и реагируют на чрезвычайные ситуации" to the page content. With Firefox 59.0.3 (Windows machine, Clear Type turned on), @akudinova477 found that some of the characters are rendered taller than others:
![image](https://user-images.githubusercontent.com/2125181/43478627-33757a00-94b3-11e8-9286-c7ac7106bc71.png)
blowup:
![image](https://user-images.githubusercontent.com/2125181/43478823-c72f799e-94b3-11e8-9837-92946ccec55f.png)

Sample website: http://localgovtemplates2.esri.com/support/fonts/ru.html

I have not been able to reproduce the problem using using FF 59.0.3, 60.0.2, 61.0.1, 62.0b12 on a Windows machine, but Anna can reproduce it reliably using the sample website as well as another calcite-web-based app.

**Comment by paulcpederson** [comment] 2018-08-04 00:51
@MikeTschudi I am having trouble recreating this. I am not seeing what is shown in the screenshot. In 59.0.3 it looks like this for me:

![d642726de26541c4536304009cfe77ec](https://user-images.githubusercontent.com/1031758/43670840-aef4ef64-9745-11e8-96e1-41091ca87b47.png)


I've tried Mac and Debian Linux as well and just can't reproduce. Any more info? Also, does the problem persist after @akudinova477 updates firefox to latest? Wondering if it is some system setting or something?

**Comment by akudinova477** [comment] 2018-08-06 17:30
@paulcpederson I've updated FF to the latest version 61.0.1, the font still looks the same
![image](https://user-images.githubusercontent.com/17889173/43731390-358cdfb8-9963-11e8-97e2-ecacde9eafaa.png)

just noticed, if I increase zoom level to 110%, the font looks ok 
![image](https://user-images.githubusercontent.com/17889173/43731451-689e04cc-9963-11e8-9c7c-a7e587ca9c58.png)

Probably it's something wrong my system settings

**Comment by paulcpederson** [comment] 2018-08-06 18:37
@akudinova477 ok, I'm going to close this out for now, but feel free to open again if we can change anything in Calcite Web to fix this for you.

**Closed by paulcpederson** 2018-08-06 18:37 UTC
