### ISSUE TITLE
Responsive image solutions

### ISSUE THREAD

**Issue by jhough10** [Esri/calcite-web#524] opened 2016-03-31 21:45 UTC
POC of what responsive image solutions we can utilize and how we support that moving forward both in the framework and within our CMS.

- [ ] `picture`
- [ ] `src-set`
- [ ] `source`

**Articles for reference:**
- http://alistapart.com/article/responsive-images-in-practice
- https://responsiveimages.org/

**Comment by paulcpederson** [comment] 2016-03-31 21:47
possible duplicate of #516 ?

**Comment by jhough10** [comment] 2016-03-31 21:48
@paulcpederson @nikolaswise told me to do it. You can close. I will use that one to build against.

**Comment by nikolaswise** [comment] 2016-03-31 21:49
lol

**Comment by jhough10** [comment] 2016-03-31 21:58
All issues were closed opening one of them. :+1:

**Comment by nikolaswise** [comment] 2016-04-07 16:34
Doing some thinking and exploring about this. I'm not totally sure that there is anything that we can do at the framework level to support this, since it's pretty deeply reliant on markup and assets - things that we have basically no control over from this repo.

The *best* solution would be to dynamically generate the following markup based on a spec for image names:

```
<img srcset="image-large.jpg  1920w, 
             image.jpg        960w,
             image-small.jpg  480w"
     src="image.jpg"
     alt="Useful Alt Text">
```

With a standard naming convention and standard widths for assets, this could be done as a ruby or node helper, happen on a server whenever we have one and during template rendering in deploy whenever we don't. Assuming we have template rendering. Do it by hand if all else fails.

What we can do in Calcite Web is document this as a spec, under a generic component section called 'images' or something, just talk about the default markup structure. 

What I need to do this:
- [ ] Three default pixel widths assets will be generated at
- [ ] Naming convention for these assets

I think this basic approach will give us some serious savings in small-screen environments while still being hands of and largely automated. Savings can be expanded, but it requires much more intense art direction at the moment-by-moment level that I don't think is feasible for our scale of operations.

**Comment by jhough10** [comment] 2016-04-07 19:47
The three default sizes would work for one component, but are we envisioning needing different pixel ratios for different images that aren't full screen? If we had a grid layout of images four across then those images would never need to be 1920 at their largest and thus would force a larger image than necessary to be downloaded regardless of device. Would it be prudent to work up image ratios for each component then?

For the naming convention I think adding something to the end of the file name before the extension would work, but would we want to include the size in the filename in order to figure out the sizes for the use cases where we might have different image sizes for each component.

```
<img srcset="image-1920-lg.jpg  1920w, 
             image-960-md.jpg        960w,
             image-480-sm.jpg  480w"
     src="image.jpg"
     alt="Useful Alt Text">
```

**Comment by nikolaswise** [comment] 2016-04-07 20:57
Good point, @jhough10. We would want to do a set of three or so 'default' sets.

1. Fullscreen images (1920, 960, 480)
2. Halfscreen images (960, 480, 240)
3. Thirdscreen images (640,  320, 160)

Or something.

**Comment by jhough10** [comment] 2016-04-07 21:22
@nik that would work.

**Comment by nikolaswise** [comment] 2016-04-07 21:24
@jhough10 :+1: Who will give me the final call on the semantics?

**Comment by jhough10** [comment] 2016-04-07 21:26
@nikolaswise we look like some responsible adults to make that decision, but I think it would be best to pitch this through Stefanie to get her feedback.

**Comment by jhough10** [comment] 2016-04-07 21:35
Do we want to build a prototype to show this working? I can start working on that next week.

**Comment by nikolaswise** [comment] 2016-04-08 16:52
Documented the spec and built a small working sample in #536

**Comment by nikolaswise** [comment] 2016-04-08 16:58
Closing this issue to get it out the inbox. Open a new issue or just PR on final syntax.

**Closed by nikolaswise** 2016-04-08 16:58 UTC
Labels: enhancement
